# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
  export ZSH=/home/matti/.oh-my-zsh

# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

ZSH_THEME="robbyrussell"
# CASE_SENSITIVE="true"
# HYPHEN_INSENSITIVE="true"
# DISABLE_AUTO_UPDATE="true"
# export UPDATE_ZSH_DAYS=13
# DISABLE_LS_COLORS="true"
# DISABLE_AUTO_TITLE="true"
# ENABLE_CORRECTION="true"
# COMPLETION_WAITING_DOTS="true"
# DISABLE_UNTRACKED_FILES_DIRTY="true"
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

export EDITOR='vim'

HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_IGNORE_ALL_DUPS
setopt extendedglob nomatch notify
unsetopt appendhistory beep
bindkey -e
bindkey "^F" forward-word
bindkey "^B" backward-word

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/matti/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# The following lines were added by mee
PATH=$PATH:~/.local/bin

eval "`dircolors -b`"
alias dir='dir --color=auto'
alias grep='grep --color=auto'
alias octave='octave --no-gui -q'
alias cd..='cd ..'
alias ec2table='aws ec2 describe-instances --query \
    \ "Reservations[*].Instances[].{type: InstanceType, state: State.Name, id : InstanceId, publicIp : PublicIpAddress}" --output table'
alias ec2start="aws ec2 start-instances --instance-ids"
alias ec2end="aws ec2 stop-instances --instance-ids"
alias ec2rds='aws rds describe-db-instances --region eu-west-1 --query "DBInstances[*].{aname: DBName, engine: Engine, version: EngineVersion}" --output table'
