# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/home/matti/.oh-my-zsh

ZSH_THEME="robbyrussell"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git stack pip virtualenv kubectl rust)

source $ZSH/oh-my-zsh.sh

export EDITOR='vim'

HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000

setopt HIST_IGNORE_ALL_DUPS
setopt extendedglob nomatch notify
unsetopt appendhistory beep
bindkey -e
bindkey "^F" forward-word
bindkey "^B" backward-word

# The following lines were added by compinstall
zstyle :compinstall filename '/home/matti/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

PATH=$PATH:~/.local/bin

eval "`dircolors -b`"
alias dir='dir --color=auto'
alias grep='grep --color=auto'
alias octave='octave --no-gui -q'
alias cd..='cd ..'
alias tmux='TERM=screen-256color-bce tmux'

alias ec2table='aws ec2 describe-instances --query \
    \ "Reservations[*].Instances[].{type: InstanceType, state: State.Name, id : InstanceId, publicIp : PublicIpAddress}" --output table'
alias ec2start="aws ec2 start-instances --instance-ids"
alias ec2end="aws ec2 stop-instances --instance-ids"
alias ec2rds='aws rds describe-db-instances --region eu-west-1 --query "DBInstances[*].{aname: DBName, engine: Engine, version: EngineVersion}" --output table'
ecrtags () {
    aws ecr describe-images --repository-name $1 --query 'imageDetails[*].{tag: imageTags[0], pushed: imagePushedAt}' --output table
}
source ~/.nix-profile/etc/profile.d/nix.sh
