#!/bin/bash
 
export PATH="$HOME/bin:$PATH"
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0

# Load resources
 
xrdb -merge .Xresources
 
# Set up an icon tray
 
trayer --edge top --align right --SetDockType true --SetPartialStrut true \
 --expand true --width 10 --transparent true --tint 0x191970 --height 17 &

# Set the background color
 
xsetroot -solid midnightblue
xset r rate 300 25
xinput --set-prop "TPPS/2 IBM TrackPoint" "libinput Accel Speed" -0.2
 
# Fire up apps
 
if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

if [ -x /usr/bin/volumeicon ] ; then
   volumeicon &
fi

DROPBOXDIST=/home/matti/.dropbox-dist
DROPBOXDIR=$DROPBOXDIST/dropbox-lnx.x86_64-`cat $DROPBOXDIST/VERSION`
$DROPBOXDIR/dropbox start &
