#!/bin/bash
 
export PATH="$HOME/bin:$PATH"
# Load resources
 
xrdb -merge .Xresources
 
# Set up an icon tray
 
trayer --edge top --align right --SetDockType true --SetPartialStrut true \
 --expand true --width 10 --transparent true --tint 0x191970 --height 17 &

# Set the background color
 
xsetroot -solid midnightblue
xset r rate 300 25
 
# Fire up apps
 
if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

DROPBOXDIR=/home/matti/.dropbox-dist/dropbox-lnx.x86_64-41.4.80
$DROPBOXDIR/dropbox start &
